import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { NavBar } from '@/app/components/layout'

export const metadata: Metadata = {
  title: 'Eventos',
  description: 'Generated by create next app',
}

const LayoutEvents = ({ children }: { children: ReactNode }) => {
  return (
    <div className="wrapper">
      <NavBar />

      <main>{children}</main>
    </div>
  )
}

export default LayoutEvents
