import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { AppProvider } from '@/main/providers'
import '@radix-ui/themes/tokens.css'
import '@radix-ui/themes/components.css'
import '@radix-ui/themes/utilities.css'
import './styles/globals.css'

const montserrat = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Blog Eventos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
